#!/bin/bash

# run from git-notes as "./mkdoc"

OUTDIR="/tmp/doc2"
OUTDIR="$HOME/imli/tech/repos/sitaramc.github.com"

rm     $OUTDIR/*.html
rm -rf $OUTDIR/images
mkdir  $OUTDIR/images
rm -rf $OUTDIR/archived
mkdir  $OUTDIR/archived

for mkd in `find . -name "*.mkd" | sort`
do
    base=$(basename $mkd .mkd)
    [[ $mkd =~ archived ]] && base="archived/$base"

    md-pandoc html-N < $mkd > $OUTDIR/$base.html
done

mkdir -p   $OUTDIR/tools
cp tools/* $OUTDIR/tools
# -- XXX do we need this? -- cp images/* $OUTDIR/images

# cleanup
rm fig*.png

cd $OUTDIR
mkdir -p 1-basic-usage gcs the-list-and-irc
cp tias.html 1-basic-usage
cp gcs.html gcs/index.html
cp deploy.html the-list-and-irc
