#!/bin/bash

# run from git-notes as "./mkdoc"

OUTDIR="/tmp/doc2"
OUTDIR="$HOME/data/gits/sitaramc.github.com"

rm     $OUTDIR/*.html
rm -rf $OUTDIR/images
mkdir  $OUTDIR/images
rm -rf $OUTDIR/archived
mkdir  $OUTDIR/archived

for mkd in `find . -name "*.mkd" | sort`
do
    base=$(basename $mkd .mkd)
    [[ $mkd =~ archived ]] && base="archived/$base"

    pdh -t html-N -i $mkd -o $OUTDIR/$base.html
done

mkdir -p   $OUTDIR/tools
cp tools/* $OUTDIR/tools
# -- XXX do we need this? -- cp images/* $OUTDIR/images

# cleanup
rm fig*.png

cp index.html $OUTDIR

cd $OUTDIR
mkdir -p 1-basic-usage gcs the-list-and-irc
echo '"Try it and see" has <a href="../tias.html">moved</a>' > 1-basic-usage/tias.html
echo '"Git concepts simplified" has <a href="../gcs.html">moved</a>' > gcs/index.html
echo '"Git as a deployment tool" has <a href="../deploy.html">moved</a>' > the-list-and-irc/deploy.html
