#!/bin/bash

die() { echo "$@"; exit 1; }

integ=
verbose=
while getopts 'iv' OPTION
do
    case $OPTION in
    i)  integ=1
        ;;
    v)  verbose=1
        ;;
    ?)  echo "Usage: $0 [-i] [-v]" >&2
        exit 1
        ;;
    esac
done
shift $(($OPTIND - 1))

prefix_hdr()
{
    sed -e "1 i$1" -e 's/^/    /'
}

print_relation()
{
    while read b
    do
        git --no-pager log --oneline --left-right $1...$b |
            ( [[ -n $verbose ]] && cat || cut -c1 | sort | uniq -c ) |
            prefix_hdr $1...$b
    done
}

current_branch=$(git symbolic-ref HEAD) || die you seem to be on a detached HEAD or something
current_branch=${current_branch##refs/heads/}; echo ===== $current_branch =====; echo
local_branches=$(git for-each-ref --format='%(refname:short)' refs/heads | sort)

remotes=$(git remote)
remote_branches=$(git for-each-ref --format='%(refname:short)' refs/remotes  | sort)

# if this is an integration branch
if [[ -n $integ ]]
then
    # what local branches are not merged into it
    git branch --no-merged $current_branch |
        print_relation $current_branch |
        prefix_hdr "(local, NOT merged)"

    # what's in it that's not in the sum of all other branches
    j=
    for i in $local_branches $remote_branches
    do
        [[ $i == $current_branch ]] || j="$j ^$i"
    done
    git --no-pager log --graph '--format=%Cblue%h%Creset %Cgreen%ar%Creset %Cblue%d%Creset %s' $current_branch $j |
        prefix_hdr "EXTRA commits in integration branch"
fi

# are we in step with the similarly named remote branch?
instep()
{
    for r in $remotes
    do
        # if the list of remote branches contains our name
        # FIXME bug: will match even if $1 is a prefix of the remote branch
        if [[ $remote_branches =~ $r/$1 ]]
        then
            echo $r/$1
        fi
    done | print_relation $1
}

instep $current_branch | prefix_hdr "TRACKING status, current branch"

for b in $local_branches
do
    [[ $b == $current_branch ]] || instep $b
done | prefix_hdr "TRACKING status, other branches"

if [[ -n $verbose ]]
then
    git branch --merged $current_branch |
        prefix_hdr "local, merged branches"
    git branch -r --merged $current_branch |
        prefix_hdr "remote, merged branches"
fi
